apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "k8s-duplicator.labels" . | nindent 4 }}
  name: {{ include "k8s-duplicator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-duplicator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "k8s-duplicator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /manager
        {{- with .Values.args }}
        args:
          {{- range . }}
          - {{ . }}
          {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: metrics
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "k8s-duplicator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
