apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-duplicator.fullname" . }}
  labels:
    {{- include "k8s-duplicator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "k8s-duplicator.selectorLabels" . | nindent 4 }}
