name: publish

on:
  push:
    tags:
     - "helm-[0-9]+.[0-9]+.[0-9]+"
     - "docker-[0-9]+.[0-9]+.[0-9]+"

jobs:

  verify-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # 'contains' check fails when in detached state
          ref: "main"
          fetch-tags: true
      - name: Verify tag is for commit on main branch
        run: |
          echo "GITHUB_REF is $GITHUB_REF"
          git version
          SHA="$(git rev-parse "$GITHUB_REF")"
          echo "sha is $SHA"
          if git branch --contains "$SHA" | grep -q 'main'; then
              echo "The tag is on the main branch."
          else
              echo "The tag is not on the main branch."
              exit 1
          fi

  publish-helm:
    runs-on: ubuntu-latest
    needs: verify-tag
    if: startsWith(github.ref, 'refs/tags/helm-')
    steps:
      - uses: actions/checkout@v4
      - name: Chart version from git tag
        id: chart_version
        run: |
          GIT_TAG=${GITHUB_REF#refs/*/}
          echo "Git tag is GIT_TAG"
          CHART_VERSION=${GIT_TAG#helm-}
          echo "CHART_VERSION is $CHART_VERSION"
          echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          chart_version: "${{ steps.chart_version.outputs.chart_version }}"

  publish-docker:
    runs-on: ubuntu-latest
    needs: verify-tag
    if: startsWith(github.ref, 'refs/tags/docker-')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: |
          DOCKER_IMAGE=docker.io/nicktriller/k8s-duplicator
          # Tag must be like "docker-1.2.3"
          TAG=${GITHUB_REF#refs/tags/docker-}
          make docker-buildx IMG="docker.io/nicktriller/k8s-duplicator:$TAG"
